import type { FormulaDefinition } from "@/types/calculator";

export const FORMULA_DEFINITIONS: FormulaDefinition[] = [
  { cell: "B2", label: "Rate base", formula: "B2 = A2", valueType: "rate", group: "Rates" },
  {
    cell: "B3",
    label: "Rate at 98%",
    formula: "B3 = A2 × 98%",
    valueType: "rate",
    group: "Rates",
  },
  {
    cell: "B4",
    label: "Rate at 96%",
    formula: "B4 = A2 × 96%",
    valueType: "rate",
    group: "Rates",
  },
  {
    cell: "D2",
    label: "Current quantity at 125%",
    formula: "D2 = C2 × 125%",
    valueType: "quantity",
    group: "Current agreement quantities",
  },
  {
    cell: "D3",
    label: "Current quantity at 15%",
    formula: "D3 = C2 × 15%",
    valueType: "quantity",
    group: "Current agreement quantities",
  },
  {
    cell: "D4",
    label: "Current quantity balance",
    formula: "D4 = A9 - (D2 + D3)",
    valueType: "quantity",
    group: "Current agreement quantities",
  },
  {
    cell: "E2",
    label: "Special-condition quantity tier 1",
    formula: "E2 = D2",
    valueType: "quantity",
    group: "Current agreement quantities",
  },
  {
    cell: "E3",
    label: "Special-condition quantity tier 2",
    formula: "E3 = D3",
    valueType: "quantity",
    group: "Current agreement quantities",
  },
  {
    cell: "E4",
    label: "Special-condition quantity balance",
    formula: "E4 = A9 - (E2 + E3)",
    valueType: "quantity",
    group: "Current agreement quantities",
  },
  {
    cell: "F2",
    label: "Amount tier 1",
    formula: "F2 = E2 × B2",
    valueType: "money",
    group: "Current bill totals",
  },
  {
    cell: "F3",
    label: "Amount tier 2",
    formula: "F3 = E3 × B3",
    valueType: "money",
    group: "Current bill totals",
  },
  {
    cell: "F4",
    label: "Amount tier 3",
    formula: "F4 = E4 × B4",
    valueType: "money",
    group: "Current bill totals",
  },
  {
    cell: "F5",
    label: "Total after special condition",
    formula: "F5 = F2 + F3 + F4",
    valueType: "money",
    group: "Current bill totals",
  },
  {
    cell: "I2",
    label: "Total before special condition",
    formula: "I2 = A2 × A9",
    valueType: "money",
    group: "Current bill totals",
  },
  {
    cell: "J2",
    label: "Total after special condition",
    formula: "J2 = F5",
    valueType: "money",
    group: "Current bill totals",
  },
  {
    cell: "E9",
    label: "Previous bill quantity tier 1",
    formula: "E9 = IF(D9 < D2, D9, E2)",
    valueType: "quantity",
    group: "Previous bill calculations",
  },
  {
    cell: "E10",
    label: "Previous bill quantity tier 2",
    formula: "E10 = MAX(0, IF(D9 < D2 + D3, D9 - D2, E3))",
    valueType: "quantity",
    group: "Previous bill calculations",
  },
  {
    cell: "E11",
    label: "Previous bill quantity balance",
    formula: "E11 = MAX(0, D9 - (E9 + E10))",
    valueType: "quantity",
    group: "Previous bill calculations",
  },
  {
    cell: "F9",
    label: "Previous amount tier 1",
    formula: "F9 = E9 × B2",
    valueType: "money",
    group: "Previous bill calculations",
  },
  {
    cell: "F10",
    label: "Previous amount tier 2",
    formula: "F10 = E10 × B3",
    valueType: "money",
    group: "Previous bill calculations",
  },
  {
    cell: "F11",
    label: "Previous amount tier 3",
    formula: "F11 = E11 × B4",
    valueType: "money",
    group: "Previous bill calculations",
  },
  {
    cell: "F12",
    label: "Previous bill total after special condition",
    formula: "F12 = F9 + F10 + F11",
    valueType: "money",
    group: "Previous bill calculations",
  },
  {
    cell: "C16",
    label: "Amount payable before special condition",
    formula: "C16 = I2 - (D9 × A2)",
    valueType: "money",
    group: "Final payable amounts",
  },
  {
    cell: "D16",
    label: "Amount payable after special condition",
    formula: "D16 = J2 - F12",
    valueType: "money",
    group: "Final payable amounts",
  },
];

export const FORMULA_BY_CELL: Record<string, FormulaDefinition> = Object.fromEntries(
  FORMULA_DEFINITIONS.map((definition) => [definition.cell, definition]),
);

export const FORMULA_GROUP_ORDER = [
  "Rates",
  "Current agreement quantities",
  "Current bill totals",
  "Previous bill calculations",
  "Final payable amounts",
] as const;
